micronaut:
  application:
    name: fitness-api
  rabbitmq:
    uri: amqp://guest:guest@localhost:5672
  server:
    port: 8080
    cors:
      enabled: true

  router:
    static-resources:
      # onde o spec gerado ficará
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      # onde ficam os arquivos do UI
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  openapi:
    enabled: true
    file-name: fitness-api            # gera META-INF/swagger/fitness-api.yml
    swagger-ui:
      enabled: true
      # define um “bookmark” para a URL do seu spec dentro do UI
      urls:
        - name: "Fitness API"
          url: "/swagger/fitness-api-1.0.yml"

  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "thisisaverysecurejwtkeywith32chars"

  http:
    services:
      default:
        read-timeout: 10s
        connect-timeout: 5s

  validation:
    exception-on-failure: true

  introspection:
    packages:
      - com.yurimartins.fitness.domain

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE-DROP
    dialect: H2
    autoCommit: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

---
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

---
swagger:
  enabled: true
  title: Fitness API
  version: 1.0
  paths:
    /swagger-ui: /swagger-ui

openapi:
  enabled: true
  server:
    url: http://localhost:8080
